In [1]:
import numpy as np

In [4]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[2,1],[4,3]])
print("Addition of matrices: \n", a1+a2)

Addition of matrices: 
 [[3 3]
 [7 7]]


In [12]:
result = [[0 for _ in range(len(a2[0]))] for _ in range(len(a1))]
for i in range(len(a1)):       
    for j in range(len(a2[0])): 
        for k in range(len(a2)): 
            result[i][j] += a1[i][k] * a2[k][j]
print("Multiplication of matrices: \n",result)

Multiplication of matrices: 
 [[10, 7], [22, 15]]


In [17]:
res = np.dot(a1, a2)
print("Multiplication of matrices(using numpy): \n",res)

Multiplication of matrices(using numpy): 
 [[10  7]
 [22 15]]


In [18]:
def addition(a,b):
    print("Addition: ",a+b)
def subtraction(a,b):
    print("Subtraction: ",a-b)    
def product(a,b):
    print("Product: ",a*b)
def divide(a,b):
    print("Division: ",a/b)
def modulo(a,b):
    print("Remainder: ",a%b)
addition(10,5)
subtraction(10,5)
product(10,5)
divide(10,5)
modulo(10,5)

Addition:  15
Subtraction:  5
Product:  50
Division:  2.0
Remainder:  0


In [19]:
def fact(n):
    if n==0 or n==1 :
        return 1
    else:
        return n*fact(n-1)
fact(5)

120

In [20]:
def cumulative_product(numbers):
    if not numbers:
        return []
    result = [numbers[0]]
    for i in range(1, len(numbers)):
        result.append(result[-1] * numbers[i])
    return result
numbers = [1, 2, 3, 4, 5]
print(cumulative_product(numbers))

[1, 2, 6, 24, 120]


In [ ]:
def reverse(lis):
    reverseList=lis[::-1]
    print(reverseList)
