In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [4]:
print(arr[1:5])              #3
print(arr[4:]) 
print(arr[:4]) 
print(arr[-3:-1]) 
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7 8 9]
[1 2 3 4]
[7 8]
[2 4]
[1 3 5 7 9]


In [5]:
np.sqrt(arr)                 #4
np.std(arr)

2.581988897471611

In [6]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
print("vstack:",np.vstack((arr1,arr2)))
print("hstack:",np.hstack((arr1,arr2)))
print("ravel:",np.ravel(arr))

vstack: [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
hstack: [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
ravel: [1 2 3 4 5 6 7 8 9]


In [10]:
searchingInArray= np.array([10, 32, 30, 50, 20, 82, 91, 45])
i = np.where(searchingInArray== 30)
print(i)

(array([2], dtype=int32),)
